THERE WAS A TURTLE AND RABBIT.THE RABBIT WAS VERY CONCERNED ABOUT HIS RUNNING SPEED AS HE WAS FASTER THAN THE TURTLE.
SO THE RABBIT DECIDED TO HAVE A RACE BETWEEN HIM AND THE TURTLE.THE RACE GOT STARTED.THE RABBIT WAS RUNNING VERY FAST.
SO, WHEN THE RABBIT WAS ABOUT TO WIN THE RACE, HE DECIDED TO TAKE A SMALL NAP.WHEN HE WAKED UP HE SAW THAT THE TURTLE 
HAS WIN THE GAME.THE RABBIT WAS VERY SAD.
MORAL- DON'T BE OVERCONFIDENT
THEN FROM THAT DAY BOTH BECOME GOOD FRIENDS.
ASDDTRTRRHTNRF
